version: "3.9"
services:
  default_app: &default_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    env_file:
      - .env.development
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - rails_cache:/app/tmp/cache

  app:
    <<: *default_app
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - worker
      - cron_job

  db:
    image: postgres:14.0-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.development
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - ./redis-data:/data
  worker:
    <<: *default_app
    command: bundle exec sidekiq -C config/sidekiq.yml
  cron_job:
    <<: *default_app
    command: bundle exec whenever -c && bundle exec whenever --update-crontab && touch ./log/cron.log

volumes:
  db:
  redis:
  bundle:
  rails_cache:
